### PR TITLE
Move image parameters to the root

### PR DESCRIPTION
**Pull request by ButterBright**

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
Do we want to control this in the same place? Like we may need to override repo and commit ID within dev stage?

**Review by hanahmily — CHANGES_REQUESTED** [review]
Please move image up to the root node. We should keep a single place to set image for both standalone and cluster

**Comment by wu-sheng** [comment]
Do we need to update docs accordingly?

**Comment by ButterBright** [comment]
Sure.

**Review by wu-sheng — APPROVED** [review]

**Review by hanahmily — APPROVED** [review]

**Pull request merged**
