### PR TITLE
Upgrade banyandb to 0.5.0

### PR DESCRIPTION
**Pull request by wankai123**

### CODE REVIEW

**Review by wu-sheng — DISMISSED** [review]

**Comment by wu-sheng** [comment]
@hanahmily Could you check why e2e fails?

**Comment by hanahmily** [comment]
> @hanahmily Could you check why e2e fails?

Since we break change the banyandb client configuration in OAP, you'd better upgrade skywalking-helm firstly.

**Comment by wu-sheng** [comment]
Yes, we did that.

**Comment by wu-sheng** [comment]
Could you lock the skywalking-helm commit ID? Use the latest seems very tricky.

**Comment by wankai123** [comment]
> Could you lock the skywalking-helm commit ID? Use the latest seems very tricky.

Where used the latest？

**Comment by wu-sheng** [comment]
Rename should be good enough. I was misguided.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
