### PR TITLE
Fix wrong value references in probes

### PR DESCRIPTION
**Pull request by kezhenxu94**

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by kezhenxu94** [comment]
@hanahmily is it intentional to set all the probes the same, especially for the `startupProbe`? How long averagely does it take to start for the data node?

**Comment by hanahmily** [comment]
> @hanahmily is it intentional to set all the probes the same, especially for the `startupProbe`? How long averagely does it take to start for the data node?

startup is different from liveness and read. Liveness and read are the same.

**Comment by kezhenxu94** [comment]
> > @hanahmily is it intentional to set all the probes the same, especially for the `startupProbe`? How long averagely does it take to start for the data node?
> 
> startup is different from liveness and read. Liveness and read are the same.

I thought they should be different, but they are the same:

# Liveness

https://github.com/apache/skywalking-banyandb-helm/blob/3cc2b414a229f4a91656495ccd7fa16941389c06/chart/templates/statefulset.yaml#L100-L113

# Startup

https://github.com/apache/skywalking-banyandb-helm/blob/3cc2b414a229f4a91656495ccd7fa16941389c06/chart/templates/statefulset.yaml#L114-L127

**Comment by hanahmily** [comment]
> > > @hanahmily is it intentional to set all the probes the same, especially for the `startupProbe`? How long averagely does it take to start for the data node?
> > 
> > 
> > startup is different from liveness and read. Liveness and read are the same.
> 
> I thought they should be different, but they are the same:
> 
> # Liveness
> https://github.com/apache/skywalking-banyandb-helm/blob/3cc2b414a229f4a91656495ccd7fa16941389c06/chart/templates/statefulset.yaml#L100-L113
> 
> # Startup
> https://github.com/apache/skywalking-banyandb-helm/blob/3cc2b414a229f4a91656495ccd7fa16941389c06/chart/templates/statefulset.yaml#L114-L127

The values at https://github.com/apache/skywalking-banyandb-helm/blob/master/chart/values.yaml#L117-L136 are different. The startup probe tends to check more frequently than liveness and readiness probes.

**Pull request merged**
